try to fix the Travis `uvloop` problem
kirr:

this fixes "uvloop"-flavour CI failures where things were failing to
install with

    RuntimeError: uvloop requires Python 3.7 or greater
    An error occurred when trying to install /tmp/tmph6b7orkdget_dist/uvloop-0.15.2.tar.gz. Look above this message for any errors that were output by easy_install.
    While:
      Installing test.
      Getting distribution for 'uvloop>=0.5.1'.

(see e.g. https://travis-ci.com/github/zopefoundation/ZEO/jobs/498522609)