Use bytes, instead of str
Seems that a leftover when upgading the code to support Python 3, the Unix version was updated but not the windows side.

UNIX SIde:
        def _physical_pull(self):
            os.write(self.trigger, b'x')

The error spitted if this patch is not applied is:

Exception in thread Connect([(<AddressFamily.AF_INET: 2>, ['127.0.0.1', 4881])]):
Traceback (most recent call last):
  File "E:\Dropbox\Projects\Python-x64-3.5.0\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "E:\Dropbox\Projects\Python-x64-3.5.0\lib\site-packages\ZEO\zrpc\client.py", line 390, in run
    success = self.try_connecting(attempt_timeout)
  File "E:\Dropbox\Projects\Python-x64-3.5.0\lib\site-packages\ZEO\zrpc\client.py", line 421, in try_connecting
    r = self._connect_wrappers(wrappers, deadline)
  File "E:\Dropbox\Projects\Python-x64-3.5.0\lib\site-packages\ZEO\zrpc\client.py", line 503, in _connect_wrappers
    wrap.connect_procedure()
  File "E:\Dropbox\Projects\Python-x64-3.5.0\lib\site-packages\ZEO\zrpc\client.py", line 589, in connect_procedure
    self.test_connection()
  File "E:\Dropbox\Projects\Python-x64-3.5.0\lib\site-packages\ZEO\zrpc\client.py", line 597, in test_connection
    self.conn = ManagedClientConnection(self.sock, self.addr, self.mgr)
  File "E:\Dropbox\Projects\Python-x64-3.5.0\lib\site-packages\ZEO\zrpc\connection.py", line 713, in __init__
    self.call_from_thread()
  File "E:\Dropbox\Projects\Python-x64-3.5.0\lib\site-packages\ZEO\zrpc\trigger.py", line 106, in pull_trigger
    self._physical_pull()
  File "E:\Dropbox\Projects\Python-x64-3.5.0\lib\site-packages\ZEO\zrpc\trigger.py", line 235, in _physical_pull
    self.trigger.send('x')
TypeError: a bytes-like object is required, not 'str'