fixup! asyncio.client: fix problems for Python before 3.8
Do not eat the exception on systems where task.cancel() is known to work ok.
Because eating exception unconditionally hides it even if the exception
was not due to cancellation.

For example with the following simulated failure

    diff --git a/src/ZEO/asyncio/client.py b/src/ZEO/asyncio/client.py
    index eb0d49ab..37607c96 100644
    --- a/src/ZEO/asyncio/client.py
    +++ b/src/ZEO/asyncio/client.py
    @@ -231,6 +231,7 @@ def verify_connection(self):

             # we do not want that several servers concurrently
             # update the cache -- lock
    +        1/0
             register_lock = self.client.register_lock
             yield register_lock.acquire()
             try:

I see nothing in neither test output nor in testing.log even with
adjusting log level to be WARN. But after hereby patch and with
testing.log starts to come with appropriate log entry about introduced
problem:

    (py3.venv) kirr@deca:~/src/wendelin/z/ZEO$ cat testing.log
    ------
    2023-01-05T09:17:57 ERROR asyncio AsyncTask exception was never retrieved
    future: <ZEO.asyncio.futures.AsyncTask object at 0x7f43c18bc940>
    Traceback (most recent call last):
      File "/home/kirr/src/wendelin/z/ZEO/src/ZEO/asyncio/futures.py", line 281, in step
        result = self.coro.send(await_result)
      File "/home/kirr/src/wendelin/z/ZEO/src/ZEO/asyncio/client.py", line 235, in verify_connection
        1/0
    ZeroDivisionError: division by zero

During my work on asyncio bits I found it very confusing sometimes when a
problem is not reported properly or at all. Properly reporting about
unretrieved future/task exceptions helps to mitigate that.