fixup! asyncio.client: Fix bugs in closing and connecting logic
Commit e89c4bc4 (asyncio.base.Protocol: Factor-out functionality to
exchange sized-messages into SizedMessageProtocol) in particular
factored out `.closed` handling from from ServerProtocol to
base.Protocol.

However later 27c0f93 (asyncio.client: Fix bugs in closing and
connecting logic) changed that closed-related logic and there is no more
base.Protocol.closed field at all.

That commit adjusted client.Protocol.close accordingly, but missed to
restore doing `self.closed = True` for server.Protocol.close.

-> Fix it.

Without the fix and with

    --- a/log.ini
    +++ b/log.ini
    @@ -6,7 +6,7 @@
     # http://www.red-dove.com/python_logging.html#config

     [logger_root]
    -level=CRITICAL
    +level=WARN
     handlers=normal

     [handler_normal]

e.g. zeo-fan-out test run emits the following errors into testing.log:

    2023-01-15T17:00:17 ERROR asyncio Exception in callback _SelectorSocketTransport._call_connection_lost(None)
    handle: <Handle _SelectorSocketTransport._call_connection_lost(None)>
    Traceback (most recent call last):
      File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 978, in _call_connection_lost
        super()._call_connection_lost(exc)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 736, in _call_connection_lost
        self._protocol.connection_lost(exc)
      File "/home/kirr/src/wendelin/z/ZEO/src/ZEO/asyncio/server.py", line 66, in connection_lost
        self.zeo_storage.notify_disconnected()
    AttributeError: 'NoneType' object has no attribute 'notify_disconnected'
    ------
    2023-01-15T17:00:17 ERROR asyncio Exception in callback _SelectorSocketTransport._call_connection_lost(None)
    handle: <Handle _SelectorSocketTransport._call_connection_lost(None)>
    Traceback (most recent call last):
      File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 978, in _call_connection_lost
        super()._call_connection_lost(exc)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 736, in _call_connection_lost
        self._protocol.connection_lost(exc)
      File "/home/kirr/src/wendelin/z/ZEO/src/ZEO/asyncio/server.py", line 66, in connection_lost
        self.zeo_storage.notify_disconnected()
    AttributeError: 'NoneType' object has no attribute 'notify_disconnected'
    ------
    2023-01-15T17:00:17 ERROR asyncio Exception in callback _SelectorSocketTransport._call_connection_lost(None)
    handle: <Handle _SelectorSocketTransport._call_connection_lost(None)>
    Traceback (most recent call last):
      File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 978, in _call_connection_lost
        super()._call_connection_lost(exc)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 736, in _call_connection_lost
        self._protocol.connection_lost(exc)
      File "/home/kirr/src/wendelin/z/ZEO/src/ZEO/asyncio/server.py", line 66, in connection_lost
        self.zeo_storage.notify_disconnected()
    AttributeError: 'NoneType' object has no attribute 'notify_disconnected'
    ------
    2023-01-15T17:00:19 ERROR asyncio Exception in callback _SelectorSocketTransport._call_connection_lost(None)
    handle: <Handle _SelectorSocketTransport._call_connection_lost(None)>
    Traceback (most recent call last):
      File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 978, in _call_connection_lost
        super()._call_connection_lost(exc)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 736, in _call_connection_lost
        self._protocol.connection_lost(exc)
      File "/home/kirr/src/wendelin/z/ZEO/src/ZEO/asyncio/server.py", line 66, in connection_lost
        self.zeo_storage.notify_disconnected()
    AttributeError: 'NoneType' object has no attribute 'notify_disconnected'
    ------
    2023-01-15T17:00:19 ERROR asyncio Exception in callback _SelectorSocketTransport._call_connection_lost(None)
    handle: <Handle _SelectorSocketTransport._call_connection_lost(None)>
    Traceback (most recent call last):
      File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 978, in _call_connection_lost
        super()._call_connection_lost(exc)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 736, in _call_connection_lost
        self._protocol.connection_lost(exc)
      File "/home/kirr/src/wendelin/z/ZEO/src/ZEO/asyncio/server.py", line 66, in connection_lost
        self.zeo_storage.notify_disconnected()
    AttributeError: 'NoneType' object has no attribute 'notify_disconnected'