asyncio.client: Fix race in between IO loop startup and ClientThread.close
Testing with py2/trollius revealed general problem that might be
affecting both py2 and py3: sometimes tests crash in ClientThread.close
with the following:

    Error in test checkBasicPersistence (ZEO.tests.testConnection.SSLConnectionTests)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/unittest/case.py", line 329, in run
        testMethod()
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/tests/ConnectionTests.py", line 313, in checkBasicPersistence
        self._storage.close()
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/ClientStorage.py", line 381, in close
        self._server.close()
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/asyncio/client.py", line 1075, in close
        super(ClientThread, self).close()
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/asyncio/client.py", line 959, in close
        run_coroutine_threadsafe(self.client.close_co(), loop))
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/asyncio/base.py", line 198, in loop_run_until_complete
        return loop.run_until_complete(fut)
      File "/home/kirr/src/tools/py/trollius/trollius/base_events.py", line 349, in run_until_complete
        self.run_forever()
      File "/home/kirr/src/tools/py/trollius/trollius/base_events.py", line 308, in run_forever
        raise RuntimeError('Event loop is running.')
    RuntimeError: Event loop is running.

which looks strange on the first glance, because ClientThread.close
first checks `if loop.is_running()` and does not start the loop anew if
it is not.

However more close inspection showed that it might be that at the time
of ClientThread.close call, the loop is not _yet_ started, and it starts
simultaneously with that close running. The close first check
`loop.is_running()`, sees False, and decides to start up the loop -
simultaneously with run_io_thread -> oops.

To justify my theory I've added the following debugging prints:

    diff --git a/src/ZEO/asyncio/client.py b/src/ZEO/asyncio/client.py
    index a71ea00f..9721e665 100644
    --- a/src/ZEO/asyncio/client.py
    +++ b/src/ZEO/asyncio/client.py
    @@ -23,6 +23,9 @@
     The loop management is the responsibility of ``ClientThread``,
     a tiny wrapper around ``ClientRunner``.
     """
    +from __future__ import print_function
    +import traceback
    +from time import sleep
     import logging
     import random
     import sys
    @@ -942,6 +945,8 @@ def close(self):
             if loop is None or loop.is_closed():  # pragma: no cover
                 # this should not happen
                 return
    +        loop_thread_id = loop._thread_id
    +        run_io_started = self._run_io_started
             if loop.is_running():
                 call(self.client.close_co())
             else:  # pragma: no cover
    @@ -949,8 +954,31 @@ def close(self):
                 #       calls hereby close with already stopped event loop.
                 # Note: run_coroutine_threadsafe - not Task - is used to protect
                 #       from executing coro steps while loop is not yet running.
    -            loop_run_until_complete(loop,
    -                    run_coroutine_threadsafe(self.client.close_co(), loop))
    +            try:
    +                loop_run_until_complete(loop,
    +                        run_coroutine_threadsafe(self.client.close_co(), loop))
    +            except:
    +                print('\n\n\n')
    +                print('loop_thread_id:', loop_thread_id)
    +                print('loop._thread_id:', loop._thread_id)
    +                print('_run_io_started:', run_io_started)
    +                print('_run_forever_done:', self._run_forever_done)
    +                print('_unexpected_close:', self._unexpected_close)
    +                print('loop: ', loop, id(loop))
    +                print('.loop:', self.loop, id(self.loop))
    +                print()
    +                stk = loop._run_by_tb
    +                if stk is not None:
    +                    print('loop._run_by_tb:')
    +                    for _ in traceback.format_list(stk):
    +                        print(_, end='')
    +                print()
    +                print('loop: ', loop, id(loop))
    +                print('.loop:', self.loop, id(self.loop))
    +                sleep(1)
    +                print('\n----')
    +                raise
             self.__args = None  # break reference cycle

         @staticmethod
    @@ -1003,20 +1031,26 @@ def __init__(self, addrs, client, cache,
             if self.exception:
                 raise self.exception

    +    _run_io_started = False
    +    _run_forever_done = False
    +    _unexpected_close = False
         exception = None

         def run_io_thread(self):
    +        self._run_io_started = True
             try:
                 loop = self.loop if self.loop is not None else new_event_loop()
                 self.setup_delegation(loop)
                 loop.call_soon(self.started.set)
                 loop_run_forever(loop)
    +            self._run_forever_done = True
             except Exception as exc:
                 logger.exception("Client thread")
                 self.exception = exc
                 self.started.set()
             finally:
                 if not self.__closed:
    +                self._unexpected_close = True
                     super(ClientThread, self).close()
                     logger.critical("Client loop stopped unexpectedly")
                 loop.close()

and what I saw was:

    loop_thread_id: None
    loop._thread_id: 140577706939968
    _run_io_started: True
    _run_forever_done: False
    _unexpected_close: False
    loop:  <_UnixSelectorEventLoop running=True closed=False debug=False> 140577707613456
    .loop: <_UnixSelectorEventLoop running=True closed=False debug=False> 140577707613456

    loop._run_by_tb:
      File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
        self.__bootstrap_inner()
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/asyncio/client.py", line 1045, in run_io_thread
        loop_run_forever(loop)
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/asyncio/base.py", line 187, in loop_run_forever
        return loop.run_forever()
      File "/home/kirr/src/tools/py/trollius/trollius/base_events.py", line 311, in run_forever
        self._run_by_tb = traceback.extract_stack(sys._getframe())

    loop:  <_UnixSelectorEventLoop running=True closed=False debug=False> 140577707613456
    .loop: <_UnixSelectorEventLoop running=True closed=False debug=False> 140577707613456

So the fact that `loop_thread_id` prints as None (it is loop._thread_id value
observed right before loop.is_running() call which uses it), and later
loop._thread_id becomes non-None proves indeed that the IO loop was not yet
started at the time when ClientThread.close was run.

-> Fix it by signalling run_io_thread readiness when the loop actually starts for real.

Before this patch I was running

    $ time while true; do zope-testrunner -fvvvvx --test-path=src -t checkBasicPersistence || break; done

and was reliably getting a failure in about one minute or less.

After this patch I was running the same command for 15 minutes without
any problem at all.