fixup! asyncio.futures: Implement cancellation thoroughly
Cython code for ConcurrentTask.cancel was missing propagating return,
which was resulting in result of the cancel being dropped instead of
returned to the caller. Fix it.

Adjust all tests to very result of cancel call. Python version was all
ok, but before the fix the pyx one was failing with

     test_cancel_from_another_thread (ZEO.asyncio.tests.ConcurrentTaskTests)Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/asyncio/tests.py", line 1772, in Tcancel
        self.assertTrue(_)
      File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
        raise self.failureException(msg)
    AssertionError: None is not true

     (0.003 s)

    Failure in test test_cancel_from_another_thread (ZEO.asyncio.tests.ConcurrentTaskTests)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/unittest/case.py", line 329, in run
        testMethod()
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/asyncio/tests.py", line 1783, in test_cancel_from_another_thread
        self.assertTrue(Tcancel.ok)
      File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
        raise self.failureException(msg)
    AssertionError: False is not true

Noticed while replying to @d-maurer here: https://github.com/zopefoundation/ZEO/pull/217#discussion_r1064344367