asyncio.base: Fix repr(Protocol)
--------
kirr:

Without the fix added test_repr crashes as

    Error in test test_repr (ZEO.asyncio.tests.ProtocolTests)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/unittest/case.py", line 329, in run
        testMethod()
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/asyncio/tests.py", line 929, in test_repr
        repr(self.loop.protocol)  # satisfied if no exception
      File "/home/kirr/src/wendelin/z/ZEO5/src/ZEO/asyncio/base.py", line 82, in __repr__
        return self.name
    AttributeError: 'Protocol' object has no attribute 'name'

The bug is that Protocol.__init__ sets .addr, but it tries to use .name
inside its __repr__. Previously it used to work somehow because
derivative classes were also setting .name by themselves.

-> Fix it my changing base.Protocol to accept name in its constructor,
and adjusting the users correspondingly. Also adjust __repr__ not to
return just the name, but also indicate fully-qualified class of self.
This is usually much more informative.

Extracted from https://github.com/zopefoundation/ZEO/pull/195 and added
base.Protocol-specific test by myself.