fixup! asyncio.futures: Mimic async/await with plain yield and @coroutine decorator
It turns out not only trollius accesses fut._exception directly: Py3.6
also does it. For example wit py3.6 the following test run hangs

    $ zope-testrunner -uvvvx --test-path=src -t test_cancel_task_while_blocked_on_async_future

with the following in testing.log

    2023-01-01T16:06:49 ERROR asyncio Exception in callback <function _run_until_complete_cb at 0x7f64ef58cd90>
    Traceback (most recent call last):
      File "/home/kirr/src/wendelin/z/ZEO/src/ZEO/asyncio/futures.py", line 105, in call_callbacks
        cb(self)
      File "/home/kirr/local/py3.6/lib/python3.6/asyncio/base_events.py", line 201, in _run_until_complete_cb
        exc = fut._exception
    AttributeError: 'AsyncTask' object has no attribute '_exception'

-> Adjust Future._exception to be provided unconditionally.